language: python
python:
  - '3.6.9'

before_script:
  - pip3 install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="OCmusic.settings.travis"

services:
  - postgresql

script:
  - flake8 . --count --show-source --statistics
  - sudo -u postgres -H -- psql -c 'CREATE DATABASE travisci;'
  - python3 manage.py migrate
  - python3 manage.py test
