# Generated by Django 3.2.4 on 2021-06-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifysession',
            name='token_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
