# Generated by Django 3.2.4 on 2021-07-14 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.CharField(max_length=128, null=True)),
                ('medium_img', models.CharField(max_length=128, null=True)),
                ('large_img', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.CharField(max_length=128, null=True)),
                ('medium_img', models.CharField(max_length=128, null=True)),
                ('large_img', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idx', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('like', models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='spotifysession',
            name='id',
        ),
        migrations.AlterField(
            model_name='spotifysession',
            name='client_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.artist')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
