# Generated by Django 3.2.4 on 2022-10-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_spotifysession_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifysession',
            name='access_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='spotifysession',
            name='token_expires',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
