# Generated by Django 3.2.4 on 2021-07-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='messsage',
            new_name='message',
        ),
    ]
